version: '2'
services:
  app:
    build:
      context: .
      args:
        rails_env: development
    volumes:
      - .:/code
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
    ports:
      - 3000:3000
    links:
      - pg
      - redis
    command: bundle exec rails server -p 3000 -b 0.0.0.0
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  pg-data: {}
  redis-data: {}
