base_locale: ca
locales: [ca,es,en]
ignore_missing:
- "add_descriptive"
- "decidim.anonymous_user"
- "decidim.authorization_handlers.errors.duplicate_authorization"
- "decidim.budgets.projects.project_budget_button.add"
- "decidim.components.comment.deleted_user"
- "decidim.core.actions.unauthorized"
- "decidim.devise.sessions.new.sign_in_disabled"
- "decidim.devise.shared.omniauth_buttons.or"
- "decidim.shared.login_modal.*"
- "decidim.system.actions.*"
- "decidim.system.models.*"
- "decidim.system.organizations.*"
- "devise.passwords.*"
- "devise.sessions.*"
- "devise.shared.*"
- "layouts.decidim.user_menu.*"
ignore_unused:
- "decidim.authorization_handlers.ephemerable"
- "decidim.components.budgets.settings.global.*"
# - "decidim.devise.sessions.*"
- "decidim.devise.shared.*"
- "decidim.events.verifications.verify_with_managed_user.*"
- "activemodel.attributes.ephemeral_participant.*"
- "activemodel.attributes.organization.allows_ephemeral_participation"
- "activemodel.attributes.organization.enabled"
- "activemodel.errors.*"