# frozen_string_literal: true

Rails.application.config.to_prepare do
  Decidim::Budgets::BudgetListItemCell.include(Decidim::Budgets::BudgetListItemCellOverride)
  Decidim::System::SystemChecksCell.include(Decidim::System::SystemChecksCellOverride)
  Decidim::System::BaseOrganizationForm.include(Decidim::System::BaseOrganizationFormOverride)
  Decidim::PaginateHelper.include(Decidim::PaginateHelperOverride)
  Decidim::Initiatives::Admin::Permissions.prepend(Decidim::Initiatives::Admin::PermissionsOverride)
  Decidim::SearchResourceFieldsMapper.prepend(Decidim::Overrides::SearchResourceFieldsMapper)
  Decidim::Initiatives::InitiativeMetadataGCell.include(Decidim::Initiatives::InitiativeMetadataGCellOverride)
  Decidim::Forms::UserAnswersSerializer.prepend(Decidim::Overrides::Forms::UserAnswersSerializer)
  Decidim::Initiative.include(Decidim::InitiativeOverride)
  Decidim::InitiativesVote.include(Decidim::InitiativesVoteOverride)
  Decidim::Initiatives::InitiativeForm.include(Decidim::Initiatives::InitiativeFormOverride)
  Decidim::Initiatives::Admin::InitiativeForm.include(Decidim::Initiatives::Admin::InitiativeFormOverride)
  Decidim::Initiatives::CreateInitiative.include(Decidim::Initiatives::CreateInitiativeOverride)
  Decidim::Initiatives::UpdateInitiative.include(Decidim::Initiatives::UpdateInitiativeOverride)
  Decidim::Initiatives::Admin::UpdateInitiative.include(Decidim::Initiatives::Admin::UpdateInitiativeOverride)
  Decidim::Initiatives::InitiativeSerializer.include(Decidim::Initiatives::InitiativeSerializerOverride)
  Decidim::Accountability::Result.include(Decidim::Accountability::ResultOverride)
  Decidim::Accountability::ResultsCalculator.include(Decidim::Accountability::ResultsCalculatorOverride)
  Decidim::Meetings::Meeting.include(Decidim::Meetings::MeetingOverride)
  Decidim::Meetings::MeetingsController.include(Decidim::Meetings::MeetingsControllerOverride)
  Decidim::Meetings::OnlineMeetingCell.include(Decidim::Meetings::OnlineMeetingCellOverride)
  Decidim::Meetings::MeetingsHelper.include(Decidim::Meetings::MeetingsHelperOverride)
  Decidim::Meetings::JoinMeetingButtonCell.include(Decidim::Meetings::JoinMeetingButtonCellOverride)
  Decidim::ContentBlocks::LastActivityCell.include(Decidim::ContentBlocks::LastActivityCellOverride)
  Decidim::ActivitiesCell.include(Decidim::ActivitiesCellOverride)
  Decidim::UserProfileCell.include(Decidim::UserProfileCellOverride)
  Decidim::Proposals::ProposalPresenter.include(Decidim::Proposals::ProposalPresenterOverride)
  Decidim::Forms::QuestionnaireUserAnswers.include(Decidim::Forms::QuestionnaireUserAnswersOverride)
  Decidim::Proposals::ApplicationHelper.include(Decidim::Proposals::ApplicationHelperOverride)
  Decidim::Assemblies::AssembliesController.include(Decidim::Assemblies::AssembliesControllerOverride)
  Decidim::Accountability::ApplicationHelper.include(Decidim::Accountability::ApplicationHelperOverride)
  Decidim::Exporters::InitiativeVotesPDF.prepend(Decidim::Overrides::Exporters::InitiativeVotesPdf)
end
