test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

s3:
  service: S3
  public: <%= Rails.application.secrets.dig(:storage, :s3, :public) %>
  access_key_id: <%= Rails.application.secrets.dig(:storage, :s3, :access_key_id) %>
  secret_access_key: <%= Rails.application.secrets.dig(:storage, :s3, :secret_access_key) %>
  bucket: <%= Rails.application.secrets.dig(:storage, :s3, :bucket) %>
  <%= "region: #{Rails.application.secrets.dig(:storage, :s3, :region)}" if Rails.application.secrets.dig(:storage, :s3, :region) %>
  <%= "endpoint: #{Rails.application.secrets.dig(:storage, :s3, :endpoint)}" if Rails.application.secrets.dig(:storage, :s3, :endpoint) %>
