name: Test
on: [push]

env:
  RUBY_VERSION: 3.0.2
  NODE_VERSION: 16.9.1

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
      redis:
        image: redis:3.2-alpine
        ports: ["6379:6379"]
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 119.0.6045.105
      - name: List Chrome
        run: apt list --installed | grep chrome
      - name: Remove Chrome
        run: sudo apt remove google-chrome-stable
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 119.0.6045.105
      - run: bundle exec rake db:test:prepare
        name: Setup database
      - name: Precompile assets
        run: |
          npm install
          bundle exec rake assets:precompile
      - run: bundle exec rspec
        name: Run specs
